
f=open("data.txt","w")
userInput=input("Enter a number :")
userInput1=input("Enter a number :")
f.write(userInput+",")
f.write(userInput1)
f=open("data.txt","r")
data=f.read()
data=data.split(',')
print("data is: ",data)
res=int(data[0])+int(data[1])
final_Result=str(res)
strInput=str(input("Enter a file name"))
f=open(strInput,"w")
f.write(final_Result)